CREATE DATABASE AULA3;

USE AULA3;

CREATE TABLE ESTADO
(
	EST_INT_ID INT NOT NULL AUTO_INCREMENT,
    EST_STR_DESC VARCHAR(70) NOT NULL,
    EST_STR_SIGLA CHAR(2) NOT NULL,
    CONSTRAINT UK_ESTADO_ID PRIMARY KEY (EST_INT_ID),
    CONSTRAINT UK_ESTADO_SIGLA UNIQUE (EST_STR_SIGLA)
    
);

CREATE TABLE CIDADE
(
	CID_INT_ID INT NOT NULL AUTO_INCREMENT,
    CID_STR_DESC VARCHAR(50) NOT NULL,
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY (CID_INT_ID)
    );
    
ALTER TABLE CIDADE
ADD CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY (EST_INT_ID)
REFERENCES ESTADO (EST_INT_ID);

SELECT * FROM ESTADO;

INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Acre', 'AC');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Alagoas', 'AL');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Amapá', 'AP');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Amazonas', 'AM');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Bahia', 'BA');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Ceará', 'CE');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Distrito Federal', 'DF');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Espírito Santo', 'ES');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Goiás', 'GO');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Maranhão', 'MA');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Mato Grosso', 'MT');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Minas Gerais', 'MG');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Pará', 'PA');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Paraíba', 'PB');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Paraná', 'PR');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Pernambuco', 'PE');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Piauí', 'PI');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Rio Grande do Norte', 'RN');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Rondônia', 'RO');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Roraima', 'RR');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Santa Catarina', 'SC');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('São Paulo', 'SP');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Sergipe', 'SE');
INSERT INTO ESTADO (EST_STR_DESC, EST_STR_SIGLA) VALUES ('Tocantins', 'TO');


SELECT 
C.CID_STR_DESC AS 'CIDADE',
S.EST_STR_DESC AS 'ESTADO',
S.EST_STR_SIGLA AS 'SIGLA'
FROM ESTADO AS S INNER JOIN CIDADE AS C ON S.EST_INT_ID = C.EST_INT_ID;